ALTER TABLE cars ADD COLUMN supplier VARCHAR(255) DEFAULT 'LEGACY' NOT NULL;
ALTER TABLE cars ADD COLUMN vehicle_type ENUM(
    'COMPACT',
    'FULL_SIZE',
    'LUXURY',
    'SUV',
    'PREMIUM_VAN'
) DEFAULT 'COMPACT' NOT NULL;
ALTER TABLE cars ADD COLUMN transmission_type ENUM(
    'AUTOMATIC',
    'MANUAL'
) DEFAULT 'MANUAL' NOT NULL;
ALTER TABLE cars ADD COLUMN fuel_type ENUM(
    'GASOLINE',
    'DIESEL',
    'ELECTRIC',
    'HYBRID'
) DEFAULT 'GASOLINE' NOT NULL;
ALTER TABLE cars ADD COLUMN seat_count INTEGER DEFAULT 5 NOT NULL;
ALTER TABLE cars ADD COLUMN unlimited_mileage BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE cars ADD COLUMN flexible_cancellation BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE cars ADD COLUMN carla_cash_eligible BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE cars ADD COLUMN collision_damage_waiver_included BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE cars ADD COLUMN taxes_and_fees_included BOOLEAN DEFAULT FALSE NOT NULL;
