-- Mirrors the MySQL bookings table for H2 integration tests.
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    start_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_car FOREIGN KEY (car_id) REFERENCES cars (id),
    CONSTRAINT chk_bookings_date_range CHECK (end_at > start_at),
    CONSTRAINT chk_bookings_total_price CHECK (total_price > 0)
);

CREATE INDEX idx_bookings_car_dates_status
    ON bookings (car_id, start_at, end_at, status);

CREATE INDEX idx_bookings_user
    ON bookings (user_id);
